ch_util/holography.py
create_from_ant_log extracts zipped logs into /tmp to read
and import into the database. This created permissions conflicts
when another user had already extracted the file. Now export
into /tmp/26mlogs/&lt;username&gt;/ instead.
Also cleanup some notifications and shorten log message.
=> fix(holography): fix multi-user bug with create_from_ant_log

ch_util/finder.py
This code block should rarely, if ever, be used.  It's only helpful
in the rare case that you're running `Finder` on a host that also
happens to be running `alpenhornd`.
=> fix(finder): Rename StorageNode.mounted to StorageNode.active

ch_util/_db_tables.py, ch_util/layout.py
The previous layout docuemntation implied you needed to pass your "real name" (whatever that is) when calling `set_user`.
This is problematic for a few reasons:
- it confuses the notion of someone's actual name and the value of the CHIMEwiki `user_real_name` field (which is what's being matched here)
- the `user_real_name` field is typically populated by sysadmins when creating a wiki account.  It's available and can be changed by users in the wiki profile page, but most wiki users don't change it nor do they even know what the value has been set to.
- There's absolutely no validation performed on the column.  I've seen misspelled names, blank names, email addresses in this column.
- There's no requirement that the values of `user_real_name` be unique.
This changes the docs to encourage …
=> doc(layout): Encourage use of username with set_user

requirements.txt
When using a `layout.Component` instance to look up a `layout.Connexion` we appear to have been affected by  https://github.com/coleifer/peewee/issues/2304 which was fixed in Peewee 3.14.1.
This was most noticeable when using `from_pair(comp1, comp2)`.
This bug is also the reason we had to make this fix: https://github.com/chime-experiment/ch_util_private/pull/34 (which didn't make any sense to me at the time)
Peewee-2 was not affected by this bug, which is why this code worked when we originally created the layout API.
=> fix(requirements): Bump peewee requirement to 3.14.1 or newer

ch_util/tools.py
There was no logic for handling `allenby_cylinder` when using `tools.py --> get_correlator_input(..., correlator="allenby")`.
This introduced the following errors when using `get_correlator_input` to query the correlator inputs for Allenby:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-f2cce6172052> in <module>
1 inputmap = tools.get_correlator_inputs(ephemeris.unix_to_datetime(f['timestamp'][0, 0]['ctime']),
----> 2                                                    correlator=None)
/usr/local/lib/python3.6/site-packages/ch_util/tools.py in get_correlator_inputs(lay_time, correlator, connect)
1235     inputlist = [
1236         _get_input_props(layout_graph, …
```
=> feat(tools): Support querying correlator inputs for CHIME/FRB Outriggers

ch_util/rfi.py, ch_util/timing.py
This is one of a set of PRs to resolve the warnings spat out by the daily pipeline with the new MPIArray
=> fix: resolve MPIArray warnings

ch_util/rfi.py, ch_util/tools.py
In its current implementation, the RFI Filter step of the daily pipeline takes ~25 minutes. Most of this time is spent taking a rolling median, and it is done in a single process. This PR should address the issue by pre-calculating a median across frequencies to flatten the auto vis. data, then distributing across the frequency axis to distribute the computation across processes.
=> Parallel RFI filtering

ch_util/tools.py
Produces the default CHIME frequency map when called instead of storing the entire array somewhere.
Used in chime-experiment/ch_pipeline#163
=> Frequency Map (2/2): Add tools to handle some frequency map ops

ch_util/rfi.py
Add specification of end times for static rfi masking so we can unmask a band if the rfi source shuts off. 
I haven't actually updated the list of bad frequencies with known end times yet.
=> Add end times to static masking

ch_util/andata.py
This PR adds `dataset_id` to the list of distributed datasets to load in `andata.CorrData`, removes the conversion from bytestring to unicode when loading datasets from file, and adds a property to `andata.CorrData` to access `dataset_id` in unicode.
This is a bit of a workaround since unicode/bytestring conversion isn't handled for distributed datasets in `caput.memh5`. I'll change this eventually.
Accompanies chime-experiment/ch_pipeline#175
=> Dataset_id (1/2): properly load distributed dataset_id dataset

ch_util/andata.py
CorrData files are loaded with the time axis index_map timestamps left-aligned. This PR modifies the index_attr time alignment attribute indicating that the `.time` property should apply a shift in order to return centre-aligned timestamps.
Related PRs:
- https://github.com/chime-experiment/ch_pipeline/pull/168
- https://github.com/radiocosmology/caput/pull/234
- https://github.com/radiocosmology/draco/pull/227
Note: This PR will fail CI checks until the `caput` PR is merged
=> Timestamp Alignment(3/4): Modify time axis alignment attribute when reading acq data

ch_util/tools.py
Querying the layout db for "KKO" or "kko" should return the KKO inputs. Currently only accepting pco.
Also adds support for GBO.
=> fix: alias name kko to FCA in get_correlator_inputs

ch_util/rfi.py
Enables `rfi.py:frequency_mask()` to accept an "instrument" parameter, so it will return a custom frequency mask for each outrigger site and CHIME.
The KKO mask is set up to cover several consistently contaminated frequency bins. Similar masks will be added for GBO and HCO when we have more/any data from each.
=> feat: site-specific frequency bin masking, adding KKO mask

ch_util/rfi.py
Setting the default timestamp to `time.time()` would potentially break compatibility with the cosmology daily pipeline since the current time does not necessarily have any relation to the CSD being processed. 
For example, if an old day did not provide a timestamp, a band which has turned off since then would not get flagged when using the current time as a timestamp even though the band was still active when that data was collected. 
I'm not sure if using the current time is needed for outrigger masking - if so, it should probably be moved to a separate place so that we maintain compatibility with the analysis pipeline.
=> fix(rfi): remove automatic timestemp set and move default instrument to argument

ch_util/tools.py
@bandersen441 noticed that the signs of KKO and GBO were incorrectly assigned while generating ringmaps for GBO. Addressing this issue now by quickly swapping signs.
=> fix(tools): Swapped sign of KKO and GBO rotation

ch_util/rfi.py
While these bands end at an earlier time, issues with gain calibration resulted in them continuing to be bad until the updated time.
Closes chime-experiment/Pipeline#125
=> feat(rfi): extend end time of two rfi bands

.github/workflows/main.yml, ch_util/rfi.py
Three things:
- Add the band from 517.97 to 524.60 MHz. We've been masking this in delay spectra, but it wasn't included in the static mask
- Extend the end time of the two bands which had gain issues from ~August 2022 - April 2023. This should now be the true date at which those issues went away
- Reorder bands by increasing frequency, grouped by bad bands at first light and bad bands that have been discovered since. I'm not sure if it really matter to group them like that, but that's how it was before so I figure we may as well leave it as-is
=> Chime static RFI mask changes

.github/workflows/main.yml, .github/workflows/sphinx.yml, ch_util/__init__.py, ch_util/cal_utils.py, ch_util/chan_monitor.py, ch_util/rfi.py, ch_util/tools.py, doc/conf.py, doc/requirements.txt, scripts/singleuse/generate_archive_test_data_2_X.py, scripts/singleuse/generate_archive_test_data_3_X.py, scripts/update_psrcat.py, tests/data_paths.py, tests/test_andata_archive2.py, tests/test_andata_dist.py, tests/test_ephemeris.py
1. Add some extra narrow bands which were previously being masked elsewhere
2. Extend an existing band to properly mask the edge
1. Update deprecated `intersphinx mapping` syntax 
2. Use python 3.11 for sphinx
3. Remove sphinx version pin
1. Bump CI linting and docs from python 3.10 to 3.11
Also, there's a black update.
=> CHIME static RFI adjustments

ch_util/_db_tables.py, ch_util/finder.py
Remove hard-coded `ntries` argument in finder and db_tables
=> Remove 'ntries' database connection argument

ch_util/ephemeris.py, requirements.txt
Add function to convert ICRS equatorial coordinates to CHIME/FRB beam-model XY coordinates
Should do the same as the CHIME/FRB beam-model utility `get_position_from_equatorial`:
https://github.com/CHIMEFRB/beam-model/blob/068e410a99bfb18e469a878e659c26393278874f/beam_model/utils.py#L122
=> feat(ephemeris): add convert ICRS to beam-model XY

ch_util/tools.py
A convenience function to convert from beam indices going from 0 through 1023 to the ones used in the CHIME/FRB `beam_model` package (and other places?) that are of the form 0-255, 1000-1255, etc.
=> feat(tools): add function to convert beam index

ch_util/ephemeris.py
This is currently set up as follows:
- You can provide either a position on the sky as a `skyfield.starlib.Star` object or an HFB source name as a string (which will be looked up in the HFB catalog).
- You provide a list of unix times of length `T` and a list of rest frequencies of length `F`, and you get out an array of Doppler shifted frequencies of shape `(F, T)`.
- In case the source is in the HFB catalog, you can omit the rest frequency, in which case the rest frequency of the absorption feature as listed in the catalog will be used.
We could also split it up into a base function for Doppler shifting (to be used in a pipeline task) and a convenience function for quickly getting Doppler shifted frequencies of HFB sources with known absorption feature frequencies.
I'll work on the …
=> Doppler shift due to Earth's motion and rotation

.github/workflows/main.yml, requirements.txt, setup.py
Python 3.8 is reaching end-of-life in October. I think we're OK to update this one, but we should be careful with deploying since some machines might be running python <= 3.8
=> Update minimum supported python to 3.9

ch_util/ephemeris.py, ch_util/holography.py, requirements.txt
In https://github.com/radiocosmology/caput/pull/269:
* `ch_util.ephemeris.sphdist` has been moved to `caput.interferometry.sphdist`
* `drift.telescope.cylbeam.rotate_ypr` has been moved to `caput.interferometry.rotate_ypr`
Updated `ch_util/holography.py` to use the caput version of `sphdist` directly.
This removes the `driftscan` dependency.
(I don't know if anything else besides the holography module uses `sphdist`, but I see no harm in re-importing it to `ephemeris`.)
=> feat(ephemeris): Import functions moved to caput

ch_util/ephemeris.py, ch_util/hfbcat.py
This isn't going to go with the rest of the ephemeris code to the new repository, so let's put is somewhere else.
Weirdly, the original docstring for this function seems to indicate it was meant to go in `tools`, but since its hardcoded to work work only on the `HFBCatalog` putting it in `hfbcat` directly seems most intuitive.
The re-constituted stub in `ephermis` avoids the circular import.
=> feat(hfbcat): Move get_doppler_shifted_freq from ephemeris

ch_util/fluxcat.py, ch_util/hfbcat.py, ch_util/tools.py
The private function `fluxcat._ensure_list` has escaped, so let's make a public version of this very generic thing in `tools`.
It's sets a bad precedent to be importing private functions.
=> fix(tools): Provide public `ensure_list` function

ch_util/andata.py, ch_util/cal_utils.py, ch_util/chan_monitor.py, ch_util/data_quality.py, ch_util/finder.py, ch_util/fluxcat.py, ch_util/holography.py, ch_util/layout.py, ch_util/plot.py, ch_util/timing.py, ch_util/tools.py
This changes imports of objects moved from `ch_util.ephemeris` to `caput.time` to use the `caput.time` version directly, rather than importing that same `caput` object via its import into `ephemeris`.
This is more prep-work for splitting `ch_util.ephemeris`.
=> fix(ch_util): Import objects directly from caput.time

ch_util/tools.py
ch_pipeline uses it, so it shouldn't be private.
Also moved the private _26M_B constant into the
function using it, to prevent it leaking out of the module in the same way.
=> feat(tools): Expose PF_SPACE constant

ch_util/cal_utils.py
`coeff` is defined on the first iteration and used on subsequent iteration `(kk > 0)`.  This initializes `coeff` to None to avoid a ruff lint error.
=> fix(cal_utils): different fix for ruff linting error

ch_util/fluxcat.py, ch_util/hfbcat.py
Because it subclasses from FluxCatalog, HFBCatalog by default will inherit the class variables from FluxCatalog, but that's where FluxCatalog stores the catalogs it loads at import time.  (Which seems like a weird, and un-Pythonic, effect of importing a module.)
The side effect is that all the FluxCatalog catalogs end up in the HFBCatalog as well, which I suspect is not intended.  So here's a fix to re-initialise these class variables to nothing, so that the FluxCatalog catalogs don't pollute the HFBCatalog.
Now, only the catalogue(s) loaded explicitly into HFBCatalog will exist in it.
=> fix(hfbcat): Re-initialise class variables

ch_util/_db_tables.py, ch_util/andata.py, ch_util/cal_utils.py, ch_util/finder.py, ch_util/fluxcat.py, ch_util/ni_utils.py, ch_util/rfi.py, ch_util/timing.py, ch_util/tools.py, pyproject.toml, tests/test_andata_dist.py
This updates the code for changes to `black` and `ruff`.  It's almost entirely getting rid of the old `"%s%d" % (var1, var2)"` formatting style.
However, to simplify things, I've introduced a `tabulate` dependency to take care of rendering the results table in `finder`, instead of the Finder doing the tabulation manually.
And, just to make sure I hadn't introduced a bug, I went through the worked example in the docstring and updated it for the `tabulate`-generated tables.
=> Linting fixes

ch_util/tools.py
It looks like this typo was introduced when making ch_util compatible with ruff (see [here](https://github.com/chime-experiment/ch_util/commit/54c02c4cc86bcff56d7e00f4b8172316fc7816a4#diff-a18048ebc99bb3f79b09f8ccbc8d593e609a423e03fdb3c8b61491cff041c1e4L252)).
=> fix(tools): typo in CorrelatorInputs __repr__

ch_util/ephemeris.py
Though `ch_util.ephemeris` is deprecated, and calling via `ch_ephem` still works, I prefer having these deprecated parts of `ch_util` show the recommended replacement for the deprecated functions.
Compare:
* https://github.com/radiocosmology/caput/pull/290
* https://github.com/chime-experiment/ch_ephem/pull/8
=> fix(ephemeris): Call CIRS methods moved to caput directly

ch_util/holography_cli.py, pyproject.toml
This is a transfer of the "alpenhorn_holography" script that used to be in `ch_alpenhorn`.
Despite the name, this script is unrelated to alpenhorn.  I need to move it out of `ch_alpenhorn` so that repo can be retooled for alpenhorn-2.
Note: though I've renamed the module itself to `ch_util.holography_cli`, the installed script is still called `alpenhorn_holography` to avoid making breaking changes.
I've done some light editing to the script for the deprecation of `ch_util.ephemeris` and to get the code to conform to the required linting standard in this repository.
I guess this finally takes care of this ancient thing: https://github.com/chime-experiment/ch_alpenhorn/issues/1
=> feat(alpenhorn_holography): Moved from ch_alpenhorn

ch_util/data_index.py
See https://github.com/chime-experiment/chimedb_di/pull/28
These are old alpenhorn-1 symbols moved to `chimedb.data_index` but now no longer needed.  (They haven't been needed _here_ for a very long time).
=> refactor(data_index): Remove deprecated alpenhorn-1 functions.

ch_util/ephemeris.py, ch_util/holography.py, ch_util/tools.py
In radiocosmology/caput#298, I move the `interferometry` module to a combination of `cora` and `driftscan`. This PR fixes those imports.
~~Importantly, this adds dependency on `cora` and `driftscan`. Most dependencies are shared, but this means that `healpy` ends up being added as a dependency here. I'm open to arguments about moving all the coordinate stuff to `caput`, so I'd like thoughts.~~ Actually, coordinates were moved to `caput`.
=> Fix radiocosmology imports

ch_util/andata.py
It's faster to load the `gain` dataset over the `freq` axis, and `mpiarray` supports contiguous slicing over the distributed axis anyway.
=> Specify different distributed axes for each dataset in CorrData spec
